name: KVM Setup and Test

on:
  push:
    branches: [main, test]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  setup-and-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up environment
        run: |
          sudo apt-get update
          sudo apt-get install -y \
              qemu-kvm \
              libvirt-daemon-system \
              libvirt-clients \
              bridge-utils \
              virt-manager \
              wget \
              lsof \
              cpu-checker

          echo "REPO_ROOT=$(pwd)" >> $GITHUB_ENV

      - name: Check KVM support
        run: |
          sudo $REPO_ROOT/scripts/precheck.sh
          echo "KVM_GROUP_SET=true" >> $GITHUB_ENV

      - name: Create required directories
        run: |
          sudo mkdir -p /var/lib/libvirt/images
          sudo chmod 777 /var/lib/libvirt/images
          mkdir -p logs dist

      - name: Download Debian ISO
        run: |
          chmod +x $REPO_ROOT/download.sh
          sudo $REPO_ROOT/download.sh

      - name: Run setup script
        run: |
          chmod +x $REPO_ROOT/setup_kvm.sh
          sudo $REPO_ROOT/setup_kvm.sh

      - name: Run healthcheck
        run: |
          chmod +x $REPO_ROOT/setup_kvm.sh $REPO_ROOT/download.sh $REPO_ROOT/cleanup.sh
          chmod +x $REPO_ROOT/scripts/*.sh
          sudo $REPO_ROOT/setup_kvm.sh
        env:
          DEBIAN_FRONTEND: noninteractive # Disable interactive prompts during installation

    